# Generated by Django 5.0.2 on 2024-03-06 14:50

from django.db import migrations, models

# Migrated Pokemon model

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
